<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title> Bibliotheque </title>
    <link rel="stylesheet" href="./css/style.css" />
  </head>
  <body>
     <nav> 
       <a class="clickable" href="./index.php?action=accueil">Accueil</a>
       <a class="chercher clickable" href="./index.php?action=chercher">Chercher</a>
       <a class="clickable" href="./index.php?action=contact">Contact</a>
       <a class="clickable" href="./index.php?action=connexion">Connexion</a>
      </nav>